name: mirror
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  camera: ^0.10.5+9
  envied: ^0.5.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  geolocator: ^10.1.1
  hive: ^2.2.3
  hooks_riverpod: ^2.4.10
  http: ^1.2.0
  intl: ^0.19.0
  path: ^1.8.3
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  riverpod: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  envied_generator: ^0.5.3
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
